sudo: required
language: c

matrix:
   include:
     - env: postgres=9.4
       addons:
            postgresql: 9.4
       install:
            - sudo apt-get install postgresql-server-dev-9.4
     - env: postgres=9.5
       addons:
            postgresql: 9.5
       install:
            - sudo apt-get install postgresql-server-dev-9.5
     - env: postgres=9.6
       addons:
            postgresql: 9.6
       install:
            - sudo apt-get install postgresql-server-dev-9.6
     - env: postgres=10
       install:
            - sudo /etc/init.d/postgresql stop
            - sudo apt-get update
            - sudo apt-get install postgresql-10 postgresql-client-10
            - sudo apt-get install postgresql-server-dev-10
            - sudo pg_ctlcluster 10 main restart
            - sudo -iu postgres psql -h localhost -c 'create user travis with superuser login;'
   fast_finish: true


script:
  - make && sudo make install && make installcheck 

after_failure:
  - cat regression.diffs 

after_success:
  - bash <(curl -s https://codecov.io/bash)
