sudo: required
language: c

matrix:
   include:
     - env: postgres=9.4
       addons:
            postgresql: 9.4
       install:
            - sudo apt-get install postgresql-server-dev-9.4
     - env: postgres=9.5
       addons:
            postgresql: 9.5
       install:
            - sudo apt-get install postgresql-server-dev-9.5
     - env: postgres=9.6
       addons:
            postgresql: 9.6
       install:
            - sudo apt-get install postgresql-server-dev-9.6
     - env: postgres=10
       addons:
            postgresql: 10
       install:
            - sudo apt-get install postgresql-server-dev-10 postgresql-client-10
            - sudo service postgresql start

   fast_finish: true


script:
  - make && sudo make install && make installcheck 

after_failure:
  - cat regression.diffs 

after_success:
  - bash <(curl -s https://codecov.io/bash)
