language: c
before_install:
  - wget https://gist.github.com/rapimo/8285458/raw/ebf8308dcaa6df5a84d6fc66e3be9aafdbb22871/apt.postgresql.org.sh
  - wget https://gist.github.com/rapimo/8285458/raw/888cf73a01366b95700560316d906044b09a50d7/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
env:
  - PGVERSION=9.1
  - PGVERSION=9.2
  - PGVERSION=9.3
script: bash ./pg-travis-test.sh